import { mkdir, readFile, writeFile } from "node:fs/promises";
import os from "node:os";
import path from "node:path";
import { createConfigStore } from "../config.js";
import { commandRoots, loadCapturePatterns } from "./patterns.js";

export const HOOK_START_MARKER = "# >>> flog capture hooks >>>";
export const HOOK_END_MARKER = "# <<< flog capture hooks <<<";

export type HookInstallOptions = {
  rcPath?: string;
  shell?: "zsh" | "bash";
  configDir?: string;
  flogBin?: string;
};

export type HookUninstallOptions = {
  rcPath?: string;
  shell?: "zsh" | "bash";
};

export function wrappersPath(configDir?: string): string {
  const dir = configDir ?? path.dirname(createConfigStore().path);
  return path.join(dir, "capture-wrappers.sh");
}

export function renderWrapperScript(roots: string[], flogBin: string): string {
  const quotedBin = shellSingleQuote(flogBin);
  const lines = [
    "# Generated by flog hook install. Do not edit by hand.",
    ""
  ];
  for (const root of roots) {
    lines.push(`${root}() {`);
    lines.push(`  command ${root} "$@"`);
    lines.push(`  local __flog_status=$?`);
    lines.push(`  ${quotedBin} capture -- ${root} "$@" >/dev/null 2>&1 || true`);
    lines.push(`  return $__flog_status`);
    lines.push(`}`);
    lines.push("");
  }
  return `${lines.join("\n")}\n`;
}

export async function installHooks(
  options: HookInstallOptions = {}
): Promise<{ rcPath: string; wrappersPath: string }> {
  const configDir = options.configDir ?? path.dirname(createConfigStore().path);
  const rcPath = options.rcPath ?? defaultRcPath(options.shell);
  const flogBin = options.flogBin ?? resolveFlogBin();
  const patterns = await loadCapturePatterns(configDir);
  const roots = commandRoots(patterns);
  const wrappersFile = wrappersPath(configDir);

  await mkdir(configDir, { recursive: true });
  await writeFile(wrappersFile, renderWrapperScript(roots, flogBin), "utf8");

  const block = [
    HOOK_START_MARKER,
    `source ${shellSingleQuote(wrappersFile)}`,
    HOOK_END_MARKER
  ].join("\n");

  let existing = "";
  try {
    existing = await readFile(rcPath, "utf8");
  } catch (error) {
    if ((error as NodeJS.ErrnoException).code !== "ENOENT") {
      throw error;
    }
  }

  const next = upsertMarkedBlock(existing, block);
  await writeFile(rcPath, next.endsWith("\n") ? next : `${next}\n`, "utf8");
  return { rcPath, wrappersPath: wrappersFile };
}

export async function uninstallHooks(
  options: HookUninstallOptions = {}
): Promise<{ rcPath: string }> {
  const rcPath = options.rcPath ?? defaultRcPath(options.shell);
  let existing = "";
  try {
    existing = await readFile(rcPath, "utf8");
  } catch (error) {
    if ((error as NodeJS.ErrnoException).code === "ENOENT") {
      return { rcPath };
    }
    throw error;
  }

  const next = removeMarkedBlock(existing);
  if (next !== existing) {
    await writeFile(rcPath, next, "utf8");
  }
  return { rcPath };
}

function defaultRcPath(shell: "zsh" | "bash" = "zsh"): string {
  const home = os.homedir();
  return shell === "bash" ? path.join(home, ".bashrc") : path.join(home, ".zshrc");
}

function resolveFlogBin(): string {
  const argv1 = process.argv[1];
  if (argv1) {
    return path.resolve(argv1);
  }
  return "flog";
}

function upsertMarkedBlock(content: string, block: string): string {
  const start = content.indexOf(HOOK_START_MARKER);
  const end = content.indexOf(HOOK_END_MARKER);
  if (start >= 0 && end > start) {
    const before = content.slice(0, start).replace(/\s*$/, "\n");
    const after = content.slice(end + HOOK_END_MARKER.length).replace(/^\n*/, "\n");
    return `${before}${block}${after === "\n" ? "\n" : after}`;
  }
  const base = content.replace(/\s*$/, "");
  if (base.length === 0) {
    return `${block}\n`;
  }
  return `${base}\n\n${block}\n`;
}

function removeMarkedBlock(content: string): string {
  const start = content.indexOf(HOOK_START_MARKER);
  const end = content.indexOf(HOOK_END_MARKER);
  if (start < 0 || end < start) {
    return content;
  }
  const before = content.slice(0, start).replace(/\s*$/, "\n");
  const after = content.slice(end + HOOK_END_MARKER.length).replace(/^\n*/, "");
  const joined = `${before}${after}`;
  return joined.replace(/\n{3,}/g, "\n\n");
}

function shellSingleQuote(value: string): string {
  return `'${value.replace(/'/g, `'\\''`)}'`;
}
